services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: supporting-ticket-system
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    env_file:
      - .env
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://app:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: mysql:8.2
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-laravel_db}"
      MYSQL_USER: "${DB_USERNAME:-root_user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-root_password}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-root_password}"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ticket-service-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: "${DB_USERNAME:-root_user}"
      PMA_PASSWORD: "${DB_PASSWORD:-root_password}"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

  redis:
    image: redis:7.2
    container_name: ticket-service-redis
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - ./docker/redis:/usr/local/etc/redis:ro
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis@2024SecurePassw0rd", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: ticket-service-redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: ticket-service-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - laravel

volumes:
  dbdata:
  redisdata:

networks:
  laravel:
    driver: bridge
